---
- name: restart nginx
  service: name=nginx state=restarted

- name: restart gunicorn
  service: name=gunicorn state=restarted

- name: Restart Supervisor
  supervisorctl: name={{ project_name }} state=restarted