---
- name: install gunicorn with virtualenv
  pip: name=gunicorn virtualenv={{virtualenv_dir}}

- name: copy gunicorn config
  template: src=files/gunicorn.j2 dest=/etc/init/gunicorn.conf
  notify:
  - restart gunicorn

- name: make sure gunicorn server is running
  service: name=gunicorn state=started enabled=yes