---
- include: setup_source_code.yml
  when: "{{git_repo}}"

- include: setup_virtualenv.yml

- include: setup_django_app.yml

- include: setup_gunicorn.yml

- include: setup_supervisor.yml

- include: setup_nginx.yml