---
- name: Install python packages for Django
  pip: requirements={{ app_code_dir }}/requirements/development.txt virtualenv={{ virtualenv_dir }}

- name: django syncdb
  django_manage:
    command: syncdb
    app_path: "{{app_code_dir}}"
    virtualenv: "{{virtualenv_dir}}"
    settings: "{{django_settings}}"
    pythonpath: "{{pythonpath}}"

- name: django migrate
  django_manage:
    command: migrate
    app_path: "{{app_code_dir}}"
    virtualenv: "{{virtualenv_dir}}"
    settings: "{{django_settings}}"
    pythonpath: "{{pythonpath}}"
