---
- name: Check if virtualenv already exists
  stat: path={{virtualenv_dir}}
  register: venv_dir

- name: Create virtualenv with mysql-python installed in it
  pip: name=mysql-python virtualenv={{virtualenv_dir}}

