---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: myapp

deploy_user: vagrant

# Path source code
install_root: /home/{{deploy_user}}/sources

# the python module path to your project's wsgi file. E.g. for a directory
# layout like this (assuming `myapp` is the project_name and top level
# directory name):
# myapp
# ├── myapp
# │   ├── __init__.py
# │   ├── settings.py
# │   ├── urls.py
# │   └── wsgi.py
# ├── manage.py
# └── requirements
#     |-- base.txt
#     |-- development.txt

# the correct wsgi_module value would be `hello.wsgi`
wsgi_module: myapp.wsgi

# any directories that need to be added to the PYTHONPATH.
pythonpath: "{{install_root}}/{{project_name}}/venv/bin/python"


# the git repository URL for the project
#project_repo: git@github.com:technivore/django-hello-world.git

# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/id_rsa

# The value of your django project's STATIC_ROOT settings.
# This will be the directory that django's `collectstatic` management command
# copies static files to, and it must be an absolute path. The default value
# here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/static"

django_settings: "myapp.settings"

# server directory for the virtualenv that will be created to run the web app
virtualenv_dir: "{{install_root}}/{{project_name}}/venv"

# server directory to put the code into that is pulled from the code
# repository
app_code_dir: "{{ install_root }}/{{project_name}}"

app_log_file: "{{ app_code_dir }}/logs/gunicorn_supervisor.log"
# the dns name or names (space separated) for your server
#server_name: django-hello.com www.django-hello.com

# database setup. Note that because this playbook doesn't touch the default
# postgres pg_hba.conf file, we use local password-based authentication for
# postgres and thus you need to provide a username and password, and your
# settings.py MUST set "localhost" or "127.0.0.1" as the HOST value. For
# example, the default settings here assume the following values in
# settings.py:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST': 'localhost',
#         'NAME': 'exampledb',
#         'USER': 'root',
#         'PASSWORD': 'django@123',
#     }
# }
db_name: exampledb
db_user: root
db_password: django@123

server_name: localhost

django_env_vars: {
  DEBUG: True,
  DATABASE_URL: '', # ex: postgres://deployer@127.0.0.1:5432/dbname'
  STATIC_URL: '/static/',
  SECRET_KEY: '',
}
