---
- name: Install system packages
  apt: pkg={{ item }} update-cache={{ update_apt_cache }} force=yes state=installed
  with_items: "{{ system_packages }}"

- name: Install required Python packages.
  easy_install: name={{ item }}
  with_items: "{{ python_packages }}"